# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 985)
        MainWindow.setMaximumSize(QtCore.QSize(784, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(246, 255, 252);\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, -10, 231, 61))
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 671, 41))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 140, 71, 31))
        self.lineEdit.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 140, 71, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 140, 21, 21))
        self.label_3.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 71, 21))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                   "font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 110, 91, 21))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 140, 71, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 180, 91, 21))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 210, 71, 31))
        self.lineEdit_3.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_3.setObjectName("lineEdit_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 210, 71, 31))
        self.lineEdit_4.setObjectName("lineEdit_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 210, 71, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                   "font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 210, 21, 21))
        self.label_8.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 250, 91, 21))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 280, 71, 31))
        self.lineEdit_5.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 280, 71, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(260, 280, 71, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 250, 71, 21))
        self.label_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 280, 21, 21))
        self.label_11.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 320, 91, 21))
        self.label_12.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 350, 71, 31))
        self.lineEdit_7.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(160, 350, 71, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(260, 350, 71, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(50, 320, 71, 21))
        self.label_13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(130, 350, 21, 21))
        self.label_14.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(500, 110, 91, 21))
        self.label_15.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(390, 110, 71, 21))
        self.label_16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(470, 140, 21, 21))
        self.label_17.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(390, 140, 71, 31))
        self.lineEdit_9.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(500, 140, 71, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(600, 140, 71, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(500, 180, 91, 21))
        self.label_18.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(390, 180, 71, 21))
        self.label_19.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(470, 210, 21, 21))
        self.label_20.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(390, 210, 71, 31))
        self.lineEdit_11.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(500, 210, 71, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(600, 210, 71, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(500, 250, 91, 21))
        self.label_21.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(390, 250, 71, 21))
        self.label_22.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(470, 280, 21, 21))
        self.label_23.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(390, 280, 71, 31))
        self.lineEdit_13.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(500, 280, 71, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(600, 280, 71, 31))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(500, 320, 91, 21))
        self.label_24.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(390, 320, 71, 21))
        self.label_25.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                    "font: 10pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(470, 350, 21, 21))
        self.label_26.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(390, 350, 71, 31))
        self.lineEdit_15.setStyleSheet("border-color: rgb(246, 255, 252);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(500, 350, 71, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(600, 350, 71, 31))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(10, 390, 551, 31))
        self.label_27.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(50, 430, 171, 21))
        self.label_28.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 620, 621, 31))
        self.label_29.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.textEditParticipants = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditParticipants.setGeometry(QtCore.QRect(50, 450, 361, 161))
        self.textEditParticipants.setObjectName("textEditParticipants")
        self.lineEditNumParicipants = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumParicipants.setGeometry(QtCore.QRect(50, 660, 221, 31))
        self.lineEditNumParicipants.setObjectName("lineEditNumParicipants")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 700, 111, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Настройки"))
        self.label_2.setText(_translate("MainWindow", "1. Количество вопросов"))
        self.label_3.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Первый"))
        self.label_5.setText(_translate("MainWindow", "Последний"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_6.setText(_translate("MainWindow", "Последний"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_7.setText(_translate("MainWindow", "Первый"))
        self.label_8.setText(_translate("MainWindow", "-"))
        self.label_9.setText(_translate("MainWindow", "Последний"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_10.setText(_translate("MainWindow", "Первый"))
        self.label_11.setText(_translate("MainWindow", "-"))
        self.label_12.setText(_translate("MainWindow", "Последний"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_13.setText(_translate("MainWindow", "Первый"))
        self.label_14.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "Последний"))
        self.label_16.setText(_translate("MainWindow", "Первый"))
        self.label_17.setText(_translate("MainWindow", "-"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_18.setText(_translate("MainWindow", "Последний"))
        self.label_19.setText(_translate("MainWindow", "Первый"))
        self.label_20.setText(_translate("MainWindow", "-"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_21.setText(_translate("MainWindow", "Последний"))
        self.label_22.setText(_translate("MainWindow", "Первый"))
        self.label_23.setText(_translate("MainWindow", "-"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_24.setText(_translate("MainWindow", "Последний"))
        self.label_25.setText(_translate("MainWindow", "Первый"))
        self.label_26.setText(_translate("MainWindow", "-"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Чгк"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Квиз"))
        self.label_27.setText(_translate("MainWindow", "2. Участники"))
        self.label_28.setText(_translate("MainWindow", "Имена участников"))
        self.label_29.setText(_translate("MainWindow", "3. Количество участников в команде"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
